#!/bin/bash
#
# Cancel all active orders
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#cancel-all-orders
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]] && [[ -z $2 ]]; then
    cancelby=$(jq -c '{"type": "All"}' <<< {})

elif [[ -z $1 ]] || [[ -z $2 ]]; then
    echo "You must specify both coins in the pair"
    exit 0

else
    coin1=${1^^}
    coin2=${2^^}

    cancelby=$(jq -c --arg base ${coin1} --arg rel ${coin2} '{"type": "Pair", "data": {"base": $base, "rel": $rel}}' <<< {})
fi

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"cancel_all_orders","cancel_by":'${cancelby}',"userpass":"'${userpass}'"}')
