#!/bin/bash
source config

if [[ -z $1 ]] || [[ -z $2 ]]; then
    echo "Usage: ./checkorderbooks <base> <reL>"
    exit 0
fi

coin1=$(echo $1 | tr [a-z] [A-Z]) #uppercase
coin2=$(echo $2 | tr [a-z] [A-Z]) #uppercase

orderbooks=$(curl -s --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"orderbook\",\"base\":\"${coin1}\",\"rel\":\"${coin2}\"}")

echo "--Bids--"
printf "%-7s %-34s %20s %20s %20s\n" "Coin" "Address" "Price" "Max Volume" "Ask Price"
printf "%-7s %-34s %20s %20s %20s\n" "----" "-------" "-----" "----------" "---------"
bids=$(jq -r '(.bids[] | [.coin, .address, .price, .maxvolume, .askprice]) | @tsv' <<< $orderbooks)
echo "$bids" | awk '{printf("%-6s %35s %20.8f %20.8f %20.8f\n", $1, $2, $3, $4, $5)}'

echo
echo "--Asks--"
printf "%-7s %-34s %20s %20s\n" "Coin" "Address" "Price" "Max Volume"
printf "%-7s %-34s %20s %20s\n" "----" "-------" "-----" "----------"
bids=$(jq -r '(.asks[] | [.coin, .address, .price, .maxvolume]) | @tsv' <<< $orderbooks)
echo "$bids" | awk '{printf("%-6s %35s %20.8f %20.8f\n", $1, $2, $3, $4)}'
