#!/bin/bash
#
# Check for and enable coins needed for mm to attempt to kick start existing trades.
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#coins-needed-for-kick-start
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

for enable_coin in $(curl -s --url "http://127.0.0.1:7783" --data '{"userpass":"'${userpass}'","method":"coins_needed_for_kick_start"}' | jq -r .result[]); do
    $scriptpath/enable $enable_coin
done
