#!/bin/bash
#
# Deactivate a coin
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#disable-coin
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]]; then
    echo "You must specify a coin"
    exit 0
fi

coin=${1^^}

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"disable_coin","coin":"'${coin}'","userpass":"'${userpass}'"}')
