#!/bin/bash
#
# List currently enabled coins
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#get-enabled-coins
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"get_enabled_coins","userpass":"'${userpass}'"}')
