#!/bin/bash
#
# Display help
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#help
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

curl -s --url "http://127.0.0.1:7783" --data '{"method":"help","userpass":"'${userpass}'"}'
echo