#!/bin/bash
#
# Setup and build
# https://github.com/KomodoPlatform/atomicDEX-API#how-to-build
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

curl https://sh.rustup.rs -sSf | sh

sudo apt-get install build-essential
sudo apt-get install -y build-essential git llvm-3.9-dev libclang-3.9-dev clang-3.9 libssl-dev pkg-config jq bc gawk

rustup install nightly-2020-10-25
rustup default nightly-2020-10-25
rustup component add rustfmt-preview

cd ~
git clone https://github.com/KomodoPlatform/atomicDEX-API
cd ~/atomicDEX-API
git checkout beta-2.1.2986
cargo build --features native -vv

cd $scriptpath
git clone https://github.com/komodoplatform/coins.git

