#!/bin/bash
#
# Setup and build
# https://github.com/KomodoPlatform/atomicDEX-API#how-to-build
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ ! -f ${scriptpath}/config ]]; then
  read -p "No config file detected, do you want to set one up? (y/n)" -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      # do dangerous stuff
      cp ${scriptpath}/config.example ${scriptpath}/config
      source $scriptpath/main

      read -p "Generate random wallet passphrase? (y/n)" -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        generated_passphrase=$(rand)

        # echo $(awk -v var="passphrase" -v new_val="${generated_passphrase}" 'BEGIN{FS=OFS="="}match($1, "^\\s*" var "\\s*") {$2="" new_val}1' ${scriptpath}/config) > ${scriptpath}/config

        sed -i "s/passphrase=\"\"/passphrase=${generated_passphrase}/g" ${scriptpath}/config
      fi

      read -p "Generate random rpc userpass? (y/n)" -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        generated_userpass=$(rand)

        # echo $(awk -v var="userpass" -v new_val="${generated_userpass}" 'BEGIN{FS=OFS="="}match($1, "^\\s*" var "\\s*") {$2="" new_val}1' ${scriptpath}/config) > ${scriptpath}/config
        sed -i "s/userpass=/userpass=${generated_userpass}/g" ${scriptpath}/config
      fi
  fi
else
  source $scriptpath/main
fi

curl https://sh.rustup.rs -sSf | sh

sudo apt-get install build-essential
sudo apt-get install -y build-essential git llvm-3.9-dev libclang-3.9-dev clang-3.9 libssl-dev pkg-config jq bc gawk

rustup install nightly-2020-10-25
rustup default nightly-2020-10-25
rustup component add rustfmt-preview

cd ~
git clone https://github.com/KomodoPlatform/atomicDEX-API
cd ~/atomicDEX-API
git checkout beta-2.1.2986
cargo build --features native -vv

cd $scriptpath
git clone https://github.com/komodoplatform/coins.git

