#!/bin/bash
#
# Common startup for all scripts
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ ! -f ${scriptpath}/config ]]; then
  echo "config file does not exist, exiting"
  exit
fi

#imports
source ${scriptpath}/config
source ${scriptpath}/functions

#defaults
netid=${netid:=7777}
required_confirmations=${required_confirmations:=2}
automation=${automation:=1}
remote=${remote:=1}
default_coin_mode=${default_coin_mode:=('electrum')}
auto_enable=${auto_enable:=('KMD')}
mpm_enable=${mpm_enable:=0}
