#!/bin/bash
#
# Common startup for all scripts
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ ! -f ${scriptpath}/config ]]; then
    echo "config file does not exist, exiting"
    exit
fi

#imports
source ${scriptpath}/config

#config defaults if not set
netid=${netid:=7777}
required_confirmations=${required_confirmations:=2}
automation=${automation:=1}
remote=${remote:=1}
default_coin_mode=${default_coin_mode:=('electrum')}
auto_enable=${auto_enable:=('KMD')}
mpm_enable=${mpm_enable:=0}
#Date format for logging
datetime=${datetime:=$(date '+%Y-%m-%d %H:%M:%S')}

#more imports
source ${scriptpath}/functions

api_url="http://127.0.0.1:7783"