#!/bin/bash
#
# Starts mpm with the specified base coin.
#
# @author lightspeed393
# @link https://github.com/cipig/mmtools
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]]; then
    echo "You must specify a base coin. (BTC, KMD, BCH, LTC, or DOGE)"
    echo ""
    echo "./mpm_start KMD"
    exit 0
fi

if [[ $1 == "BTC" ]]; then
    stdbuf -oL nohup ~/mmtools/mpm/mpm.sh.dex_gecko BTC bitcoin > /tmp/mpm.log.dex.$1 &
elif [[ $1 == "KMD" ]]; then
    stdbuf -oL nohup ~/mmtools/mpm/mpm.sh.dex_gecko KMD komodo > /tmp/mpm.log.dex.$1 &
elif [[ $1 == "BCH" ]]; then
    stdbuf -oL nohup ~/mmtools/mpm/mpm.sh.dex_gecko BCH bitcoin-cash > /tmp/mpm.log.dex.$1 &
elif [[ $1 == "LTC" ]]; then
    stdbuf -oL nohup ~/mmtools/mpm/mpm.sh.dex_gecko LTC litecoin > /tmp/mpm.log.dex.$1 &
elif [[ $1 == "DOGE" ]]; then
    stdbuf -oL nohup ~/mmtools/mpm/mpm.sh.dex_gecko DOGE dogecoin > /tmp/mpm.log.dex.$1 &
else
    echo "Choose from BTC, KMD, BCH, LTC or DOGE."
fi
