#!/bin/bash
#
# Watch the output from mpm.
#
# @author lightspeed393
# @link https://github.com/cipig/mmtools
#
if [[ -z $1 ]]; then
    echo "You must specify a base coin config to edit. (BTC, KMD, BCH, LTC, or DOGE)"
    echo ""
    echo "./mpm_tv KMD"
    exit 0
fi

if [[ $1 == "BTC" ]] || [[ $1 == "KMD" ]] || [[ $1 == "BCH" ]] || [[ $1 == "LTC" ]] || [[ $1 == "DOGE" ]]; then
    tail -f /tmp/mpm.log.dex.$1
else
    echo "Choose from BTC, KMD, BCH, LTC or DOGE."
fi
