#!/bin/bash
source config

if [[ -z $1 ]]; then
    echo "You must specify a coin"
    exit 0
fi

coin=$(echo $1 | tr [a-z] [A-Z]) #uppercase

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"my_balance","coin":"'${coin}'","userpass":"'${userpass}'"}')
