#!/bin/bash
#
# Get current orders
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex-api-legacy/my_orders.html
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

my_orders=$(curl -s --url "http://127.0.0.1:7783" --data '{"method":"my_orders","userpass":"'${userpass}'"}')

echo "-- Maker Orders --"
jq -c '.result.maker_orders[] | del(.. | .max_volume_rat?,.min_base_vol_rat?,.price_rat?,.max_base_vol_rat?)' <<< ${my_orders}

echo "-- Taker Orders --"
jq -c '.result.taker_orders[] | del(.. | .max_volume_rat?,.min_base_vol_rat?,.price_rat?,.max_base_vol_rat?)' <<< ${my_orders}

echo
