#!/bin/bash
#
# Show a specific swap by UUID
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#my-swap-status
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

uuid=${1}

swapdata=$(curl -s --url "http://127.0.0.1:7783" --data '{"method":"my_swap_status","params":{"uuid":"'${uuid}'"},"userpass":"'${userpass}'"}')

echo $swapdata | jq
