#!/bin/bash
#
# Get recent tx for a coin (default 10)
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex-api-legacy/my_tx_history.html
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]]; then
    echo "You must specify a coin"
    exit 0
fi

if [[ -z $2 ]]; then
    limit=10
else
    limit=$2
fi

coin=${1^^}

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"my_tx_history","coin":"'${coin}'","limit":'${limit}',"userpass":"'${userpass}'"}')
