#!/bin/bash
#
# Get status of an active order by UUID
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#order-status
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

uuid=${1}

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"order_status","uuid":"'${uuid}'","userpass":"'${userpass}'"}')
