#!/bin/bash
#
# Get status of an active order by UUID
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex-api-legacy/order_status.html
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]]; then
    echo "You must specify the UUID"
    exit 0
fi

uuid=${1}

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"order_status","uuid":"'${uuid}'","userpass":"'${userpass}'"}')
