#!/bin/bash
cd ~/atomicDEX-API

# git pull
git fetch --all --tags
git checkout 2.0.1654

rustup install nightly-2020-02-01
rustup default nightly-2020-02-01
rustup component add rustfmt-preview

cargo build --features native -vv
