#!/bin/bash
#
# Use this to rebuild, update the tag to checkout below
#
# https://github.com/KomodoPlatform/atomicDEX-API#how-to-build
#
# @author webworker01
#
cd ~/atomicDEX-API

# git pull
git fetch --all --tags
git checkout beta-2.1.3705

rustup install nightly-2020-10-25
rustup default nightly-2020-10-25
rustup component add rustfmt-preview

cargo build --features native -vv
