#!/bin/bash
#
# Set a maker order
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#setprice
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]] || [[ -z $4 ]]; then
    echo "Usage: setprice <sellcoin> <buycoin> <price (buycoin/sellcoin)> <volume (amount or max)>"
    exit 0
fi

coin1=${1^^}
coin2=${2^^}

if [[ "$4" == "max" ]]; then
    jq '.result | del(.. | .max_volume_rat?,.min_base_vol_rat?,.price_rat?,.max_base_vol_rat?)' <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"setprice","base":"'${coin1}'","rel":"'${coin2}'","price":"'${3}'","max":true,"userpass":"'${userpass}'"}')
else
    jq '.result | del(.. | .max_volume_rat?,.min_base_vol_rat?,.price_rat?,.max_base_vol_rat?)' <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"setprice","base":"'${coin1}'","rel":"'${coin2}'","price":"'${3}'","volume":"'${4}'","userpass":"'${userpass}'"}')
fi
