#!/bin/bash
#
# Start mm2
#
# @author webowrker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

git submodule update --recursive

cp ~/mmtools/jl777coins/coins "${mmpath}coins"

cat <<EOF > ${mmpath}/MM2.json
{
    "gui": "mmtools",
    "netid": ${netid},
    "rpc_password": "${userpass}",
    "passphrase": "${passphrase}",
    "userhome": "/${HOME#\"/\"}"
}
EOF

cd ${mmpath}
stdbuf -oL nohup ./mm2 &
