#!/bin/bash
#
# Start mm2
#
# @author webowrker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

git submodule update --recursive

cp ~/mmtools/jl777coins/coins "${mmpath}coins"

cd ${mmpath}
./mm2 "{\"gui\":\"mmtools\",\"netid\":${netid}, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"${passphrase}\", \"rpc_password\":\"${userpass}\"}" &
