#!/bin/bash
#
# Get mm2 version information
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex-api-legacy/version.html
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"version","userpass":"'${userpass}'"}')
