#!/bin/bash
#
# Create a signed raw tx to send funds away.
# You must then broadcast the tx.
#
# @author webworker01
# @link https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#withdraw
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]]; then
    echo "Usage: ./withdraw <coin> <address> <amount>"
    exit 0
fi

coin1=${1^^}

if [[ "$3" == "max" ]]; then
    sendtx=$(jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"withdraw","coin":"'${coin1}'","to":"'${2}'","max":true,"userpass":"'${userpass}'"}'))
else
    sendtx=$(jq . <<< $(curl -s --url "http://127.0.0.1:7783" --data '{"method":"withdraw","coin":"'${coin1}'","to":"'${2}'","amount":"'${3}'","userpass":"'${userpass}'"}'))
fi

echo "Send the signed raw tx e.g. :"
echo "komodo-cli sendrawtransaction $(echo $sendtx | jq -r .tx_hex)"
